version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  reviewers:
  - "nscuro"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/"
  reviewers:
  - "nscuro"
  schedule:
    interval: "daily"